package com.shensu.dao;

import java.util.List;

import com.shensu.pojo.AboutMe;

public interface AboutMeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AboutMe
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AboutMe
     *
     * @mbggenerated
     */
    int insert(AboutMe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AboutMe
     *
     * @mbggenerated
     */
    int insertSelective(AboutMe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AboutMe
     *
     * @mbggenerated
     */
    AboutMe selectByPrimaryKey(Integer aboutmeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AboutMe
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AboutMe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AboutMe
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AboutMe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AboutMe
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AboutMe record);
    
    //查询关于我们的内容
    List<AboutMe> findAboutMeDetails();
    
    //增加关于我们的内容
  	int addAboutMe(AboutMe aboutMe);
  	
  	//修该关于我们的内容
  	int modifyAboutMe(AboutMe aboutMe);
}