package com.shensu.dao;

import java.util.List;

import com.shensu.pojo.FranchiseDetails;

public interface FranchiseDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer franchisedetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    int insert(FranchiseDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    int insertSelective(FranchiseDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    FranchiseDetails selectByPrimaryKey(Integer franchisedetailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FranchiseDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(FranchiseDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FranchiseDetails record);
    
	 //增加加盟页面信息
	 int addFranchiseDetails(FranchiseDetails franchiseDetails);
	 
     //查询加盟数据

     FranchiseDetails  selectFranchiseDetails(FranchiseDetails f);
     
     //查询加盟数据(小程序)
     FranchiseDetails  findFranchiseDetails(FranchiseDetails franchiseDetails);
     

     //修改加盟信息
   //  int updataFranchiseDetails(FranchiseDetails F);
     //添加修改方法

     int updataFranchiseDetails(FranchiseDetails franchiseDetails);
     
     //查询出所有的加盟者信息
     List<FranchiseDetails> HtFindFranchiseDetails();
     
     //删除所有加盟者信息
     int deleteAll();
     
     
}