package com.shensu.dao;

import java.util.HashMap;
import java.util.List;

import com.shensu.pojo.MyCard;
import com.shensu.pojo.Shop;

public interface MyCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MyCard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mycardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MyCard
     *
     * @mbggenerated
     */
    int insert(MyCard record);
    //增加卡卷的方法
    int insertSelective(MyCard record);

    MyCard selectByPrimaryKey(Integer mycardid);

    int updateByPrimaryKeySelective(MyCard record);

    int updateByPrimaryKey(MyCard record);
    //卡卷中心分页查询
	List<MyCard> selectMycardPage(HashMap<String, Object> map);
	//查询卡卷的多少
	int selectCountCard(MyCard record);
	//查询卡卷是否存在
	int selectHaveIs(MyCard record);
	//根据商品id删除优惠券
	int deleteMyCardByShopId(int shopId);
	//根据openid删除优惠券
	int deleteMyCardByOpenidId(String openId);
    
}