package com.shensu.dao;

import java.util.List;

import com.shensu.pojo.ShopType;

public interface ShopTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopType
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shoptypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopType
     *
     * @mbggenerated
     */
    int insert(ShopType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopType
     *
     * @mbggenerated
     */
    int insertSelective(ShopType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopType
     *
     * @mbggenerated
     */
    ShopType selectByPrimaryKey(Integer shoptypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopType
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShopType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopType
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShopType record);
    
    //查询全部
    List<ShopType> selectAll();
    
	//替换商品类目的展示图片
	int updateShopTypeImg(ShopType st);
	
	//根据商品类目id查询页面信息
	ShopType findShopTypeImg(int shopTypeId);
	
	//删除(设置为空)商品类目图片
	int deleteShopTypeImg(int shopTypeId);
	
	//根据商品类目id查询出商品的图片(小程序)
	List<ShopType> findShopType();
     //	//微信小程序 每个分类查询商品的前两个商品
	List<ShopType> selectShopTypeTwo();
	
	//根据商品类别名查找其id
	int getShopTypeIdByName(String shopTypeName);
	
	//查询全部类目(除了本条之外的)
	List<ShopType> editShopTypeXY(Integer shoptypeid);
}