package com.shensu.dao;

import java.util.List;

import com.shensu.pojo.ShopSwiper;

public interface ShopSwiperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shopswiperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    int insert(ShopSwiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    int insertSelective(ShopSwiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    ShopSwiper selectByPrimaryKey(Integer shopswiperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShopSwiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShopSwiper record);
    
    //根据商品查询图片
    List<ShopSwiper> selectShopSwiperByShopId(int shopId);
    
}