package com.shensu.dao;

import java.util.List;

import com.shensu.pojo.ShopSKU;

public interface ShopSKUMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSKU
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shopskuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSKU
     *
     * @mbggenerated
     */
    int insertSelective(ShopSKU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSKU
     *
     * @mbggenerated
     */
    ShopSKU selectByPrimaryKey(Integer shopskuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSKU
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShopSKU record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSKU
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShopSKU record);
    
    //增加商品SKU信息
    int insertShopSKU(ShopSKU ss);
    
    //修改商品SKU信息
  	int modifyShopSKU(ShopSKU ss);
  	
  	//根据商品shopid 查找所有shopsku
  	List<ShopSKU> findShopSKUAllByshopId(Integer shopId);
}