package com.shensu.dao;

import java.util.HashMap;
import java.util.List;

import com.shensu.pojo.Shop;
import com.shensu.pojo.ShopSwiper;


public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer shopid);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shop
     *
     * @mbggenerated
     */
    
    int updateByPrimaryKey(Shop record);
    
    //根据条件分页
    List<Shop> selectByCondition(HashMap<String,Object> map);
    
    //根据条件查总数
    int selectCountByCondition(HashMap<String,Object> map);
    
    //添加一个商品
    int insertShop(Shop s);
    
    //根据id查到一个商品
    Shop seleteByShopId(int ShopId);
    
	//添加商品图片信息
	int insertShopImg(ShopSwiper simg);
	
	//删除商品信息
	int deleteShop(Integer shopid);
	 
	//修改商品信息
    int modifyShop(Shop shop);
    
	//根据shopId删除对应的所有图片
	int deleteShopSwiperImg(int shopId);
	
	//设置商品为上架状态
	int putawayShop(int shopId);
	
	//设置商品为下架状态
	int unshelveShop(int shopId);
	
	//根据商品id删除商品呢SKU信息
	int deleteShopSKU(int shopId);
	
	//根据商品类目查询商品信息前两个(小程序)
	List<Shop> findHomePageShop(int shopTypeId);
	
	//查询商品类目下全部商品(小程序)
	List<Shop> findShopList(int shopTypeId);
	
	//根据商品id查询商品详细信息(小程序)
	List<Shop> findShopDetails(int shopId);

   //根据一个商品分类id查询多少商品

	int selectShopTypeIdCount(Shop shop);
	
	//根据shopid查询所有的轮播图、SKU、SKU轮播图
	Shop queryShopAllandSKUAll(Integer shopid);

  //根据一个商品分类id查询商品集合
	List<Shop> selectShopTypePage(HashMap<String, Object> map);
	
	//查询全部商品
	List<Shop> getAll();
	
}