package com.shensu.dao;

import java.util.List;

import com.shensu.pojo.Swiper;

public interface SwiperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Swiper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer swiperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Swiper
     *
     * @mbggenerated
     */
    int insert(Swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Swiper
     *
     * @mbggenerated
     */
    int insertSelective(Swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Swiper
     *
     * @mbggenerated
     */
    Swiper selectByPrimaryKey(Integer swiperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Swiper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Swiper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Swiper
     * @mbggenerated
     */
    int updateByPrimaryKey(Swiper record);
    
     //轮播图的增加方法
    int inserSwiper(Swiper swiper);
    
    //删除一张轮播图
    int deleteSwiper(Integer swiperid);
    
    //查询全部轮播图
	List<Swiper> findAllSwiper();
	//删除全部轮播图
	int deleteAllSwiper();
    //查询特定位置轮播图
	Swiper findByLocation(int location);
}