package com.shensu.dao;

import com.shensu.pojo.Template;

public interface TemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer templateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Template
     *
     * @mbggenerated
     */
    int insert(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Template
     *
     * @mbggenerated
     */
    int insertSelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Template
     * @mbggenerated
     */
    Template selectByPrimaryKey(Integer templateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Template
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Template
     * @mbggenerated
     */
    int updateByPrimaryKey(Template record);   
    //增加的方法
    int updateTemplate(Template t);
    
    Template selectTemplate(Template t);
    //根据openid来查询模版消息
    Template findOpenidTemplate(Template t);
   
    
}