package com.shensu.pojo;

import java.io.Serializable;

public class Admin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.adminId
     *
     * @mbggenerated
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.adminPassword
     *
     * @mbggenerated
     */
    //管理员的密码
    private String adminpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.adminAccounts
     *
     * @mbggenerated
     */
    //管理员的帐号
    private String adminaccounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.adminName
     *
     * @mbggenerated
     */
    //管理员的昵称
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.adminState
     *
     * @mbggenerated
     */
    //管理员的状态 0是超级管理员 1是普通管理员
    private Integer adminstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.adminUrl
     *
     * @mbggenerated
     */
    //管理员的头像
    private String adminurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Admin.adminCreatTime
     *
     * @mbggenerated
     */
    //管理员的创建时间
    private String admincreattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Admin
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
    
    
    public Admin(){};
    
    public Admin(String adminName, String adminPassword) {
		super();
		this.adminname = adminName;
		this.adminpassword = adminPassword;
	}
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.adminId
     *
     * @return the value of Admin.adminId
     *
     * @mbggenerated
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.adminId
     *
     * @param adminid the value for Admin.adminId
     *
     * @mbggenerated
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.adminPassword
     *
     * @return the value of Admin.adminPassword
     *
     * @mbggenerated
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.adminPassword
     *
     * @param adminpassword the value for Admin.adminPassword
     *
     * @mbggenerated
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword == null ? null : adminpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.adminAccounts
     *
     * @return the value of Admin.adminAccounts
     *
     * @mbggenerated
     */
    public String getAdminaccounts() {
        return adminaccounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.adminAccounts
     *
     * @param adminaccounts the value for Admin.adminAccounts
     *
     * @mbggenerated
     */
    public void setAdminaccounts(String adminaccounts) {
        this.adminaccounts = adminaccounts == null ? null : adminaccounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.adminName
     *
     * @return the value of Admin.adminName
     *
     * @mbggenerated
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.adminName
     *
     * @param adminname the value for Admin.adminName
     *
     * @mbggenerated
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.adminState
     *
     * @return the value of Admin.adminState
     *
     * @mbggenerated
     */
    public Integer getAdminstate() {
        return adminstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.adminState
     *
     * @param adminstate the value for Admin.adminState
     *
     * @mbggenerated
     */
    public void setAdminstate(Integer adminstate) {
        this.adminstate = adminstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.adminUrl
     *
     * @return the value of Admin.adminUrl
     *
     * @mbggenerated
     */
    public String getAdminurl() {
        return adminurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.adminUrl
     *
     * @param adminurl the value for Admin.adminUrl
     *
     * @mbggenerated
     */
    public void setAdminurl(String adminurl) {
        this.adminurl = adminurl == null ? null : adminurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Admin.adminCreatTime
     *
     * @return the value of Admin.adminCreatTime
     *
     * @mbggenerated
     */
    public String getAdmincreattime() {
        return admincreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Admin.adminCreatTime
     *
     * @param admincreattime the value for Admin.adminCreatTime
     *
     * @mbggenerated
     */
    public void setAdmincreattime(String admincreattime) {
        this.admincreattime = admincreattime == null ? null : admincreattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Admin other = (Admin) that;
        return (this.getAdminid() == null ? other.getAdminid() == null : this.getAdminid().equals(other.getAdminid()))
            && (this.getAdminpassword() == null ? other.getAdminpassword() == null : this.getAdminpassword().equals(other.getAdminpassword()))
            && (this.getAdminaccounts() == null ? other.getAdminaccounts() == null : this.getAdminaccounts().equals(other.getAdminaccounts()))
            && (this.getAdminname() == null ? other.getAdminname() == null : this.getAdminname().equals(other.getAdminname()))
            && (this.getAdminstate() == null ? other.getAdminstate() == null : this.getAdminstate().equals(other.getAdminstate()))
            && (this.getAdminurl() == null ? other.getAdminurl() == null : this.getAdminurl().equals(other.getAdminurl()))
            && (this.getAdmincreattime() == null ? other.getAdmincreattime() == null : this.getAdmincreattime().equals(other.getAdmincreattime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAdminid() == null) ? 0 : getAdminid().hashCode());
        result = prime * result + ((getAdminpassword() == null) ? 0 : getAdminpassword().hashCode());
        result = prime * result + ((getAdminaccounts() == null) ? 0 : getAdminaccounts().hashCode());
        result = prime * result + ((getAdminname() == null) ? 0 : getAdminname().hashCode());
        result = prime * result + ((getAdminstate() == null) ? 0 : getAdminstate().hashCode());
        result = prime * result + ((getAdminurl() == null) ? 0 : getAdminurl().hashCode());
        result = prime * result + ((getAdmincreattime() == null) ? 0 : getAdmincreattime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Admin
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminid=").append(adminid);
        sb.append(", adminpassword=").append(adminpassword);
        sb.append(", adminaccounts=").append(adminaccounts);
        sb.append(", adminname=").append(adminname);
        sb.append(", adminstate=").append(adminstate);
        sb.append(", adminurl=").append(adminurl);
        sb.append(", admincreattime=").append(admincreattime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}