package com.shensu.pojo;

import java.io.Serializable;

public class Fabulous implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fabulous.fabulousId
     *
     * @mbggenerated
     */
	//点赞的id
    private Integer fabulousid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fabulous.openId
     *
     * @mbggenerated
     */
    //用户的唯一标识
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fabulous.fabulousCreatTime
     *
     * @mbggenerated
     */
    //点赞的创建时间
    private String fabulouscreattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fabulous.learningWorldId
     *
     * @mbggenerated
     */
    //学习天地的ID
    private Integer learningworldid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Fabulous
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fabulous.fabulousId
     *
     * @return the value of Fabulous.fabulousId
     *
     * @mbggenerated
     */
    public Integer getFabulousid() {
        return fabulousid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fabulous.fabulousId
     *
     * @param fabulousid the value for Fabulous.fabulousId
     *
     * @mbggenerated
     */
    public void setFabulousid(Integer fabulousid) {
        this.fabulousid = fabulousid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fabulous.openId
     *
     * @return the value of Fabulous.openId
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fabulous.openId
     *
     * @param openid the value for Fabulous.openId
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fabulous.fabulousCreatTime
     *
     * @return the value of Fabulous.fabulousCreatTime
     *
     * @mbggenerated
     */
    public String getFabulouscreattime() {
        return fabulouscreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fabulous.fabulousCreatTime
     *
     * @param fabulouscreattime the value for Fabulous.fabulousCreatTime
     *
     * @mbggenerated
     */
    public void setFabulouscreattime(String fabulouscreattime) {
        this.fabulouscreattime = fabulouscreattime == null ? null : fabulouscreattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fabulous.learningWorldId
     *
     * @return the value of Fabulous.learningWorldId
     *
     * @mbggenerated
     */
    public Integer getLearningworldid() {
        return learningworldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fabulous.learningWorldId
     *
     * @param learningworldid the value for Fabulous.learningWorldId
     *
     * @mbggenerated
     */
    public void setLearningworldid(Integer learningworldid) {
        this.learningworldid = learningworldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fabulous
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Fabulous other = (Fabulous) that;
        return (this.getFabulousid() == null ? other.getFabulousid() == null : this.getFabulousid().equals

(other.getFabulousid()))
            && (this.getOpenid() == null ? other.getOpenid() == null : this.getOpenid().equals(other.getOpenid()))
            && (this.getFabulouscreattime() == null ? other.getFabulouscreattime() == null : this.getFabulouscreattime

().equals(other.getFabulouscreattime()))
            && (this.getLearningworldid() == null ? other.getLearningworldid() == null : this.getLearningworldid().equals

(other.getLearningworldid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fabulous
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFabulousid() == null) ? 0 : getFabulousid().hashCode());
        result = prime * result + ((getOpenid() == null) ? 0 : getOpenid().hashCode());
        result = prime * result + ((getFabulouscreattime() == null) ? 0 : getFabulouscreattime().hashCode());
        result = prime * result + ((getLearningworldid() == null) ? 0 : getLearningworldid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fabulous
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fabulousid=").append(fabulousid);
        sb.append(", openid=").append(openid);
        sb.append(", fabulouscreattime=").append(fabulouscreattime);
        sb.append(", learningworldid=").append(learningworldid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}