package com.shensu.pojo;

import java.io.Serializable;

public class FranchiseDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FranchiseDetails.franchiseDetailsId
     *
     * @mbggenerated
     */
	//加盟展示页面的id
    private Integer franchisedetailsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FranchiseDetails.franchiseDetailsImg
     *
     * @mbggenerated
     */
    //加盟展示图片
    private String franchisedetailsimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FranchiseDetails.franchiseDetailsCreatTime
     *
     * @mbggenerated
     */
    //加盟的展示详情的创建时间
    private String franchisedetailscreattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FranchiseDetails.franchiseDetailsContent
     *
     * @mbggenerated
     */
    //加盟的内容展示
    private String franchisedetailscontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FranchiseDetails.franchiseDetailsId
     *
     * @return the value of FranchiseDetails.franchiseDetailsId
     *
     * @mbggenerated
     */
    public Integer getFranchisedetailsid() {
        return franchisedetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FranchiseDetails.franchiseDetailsId
     *
     * @param franchisedetailsid the value for FranchiseDetails.franchiseDetailsId
     *
     * @mbggenerated
     */
    public void setFranchisedetailsid(Integer franchisedetailsid) {
        this.franchisedetailsid = franchisedetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FranchiseDetails.franchiseDetailsImg
     *
     * @return the value of FranchiseDetails.franchiseDetailsImg
     *
     * @mbggenerated
     */
    public String getFranchisedetailsimg() {
        return franchisedetailsimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FranchiseDetails.franchiseDetailsImg
     *
     * @param franchisedetailsimg the value for FranchiseDetails.franchiseDetailsImg
     *
     * @mbggenerated
     */
    public void setFranchisedetailsimg(String franchisedetailsimg) {
        this.franchisedetailsimg = franchisedetailsimg == null ? null : franchisedetailsimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FranchiseDetails.franchiseDetailsCreatTime
     *
     * @return the value of FranchiseDetails.franchiseDetailsCreatTime
     *
     * @mbggenerated
     */
    public String getFranchisedetailscreattime() {
        return franchisedetailscreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FranchiseDetails.franchiseDetailsCreatTime
     *
     * @param franchisedetailscreattime the value for FranchiseDetails.franchiseDetailsCreatTime
     *
     * @mbggenerated
     */
    public void setFranchisedetailscreattime(String franchisedetailscreattime) {
        this.franchisedetailscreattime = franchisedetailscreattime == null ? null : franchisedetailscreattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FranchiseDetails.franchiseDetailsContent
     *
     * @return the value of FranchiseDetails.franchiseDetailsContent
     *
     * @mbggenerated
     */
    public String getFranchisedetailscontent() {
        return franchisedetailscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FranchiseDetails.franchiseDetailsContent
     *
     * @param franchisedetailscontent the value for FranchiseDetails.franchiseDetailsContent
     *
     * @mbggenerated
     */
    public void setFranchisedetailscontent(String franchisedetailscontent) {
        this.franchisedetailscontent = franchisedetailscontent == null ? null : franchisedetailscontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FranchiseDetails other = (FranchiseDetails) that;
        return (this.getFranchisedetailsid() == null ? other.getFranchisedetailsid() == null : this.getFranchisedetailsid().equals(other.getFranchisedetailsid()))
            && (this.getFranchisedetailsimg() == null ? other.getFranchisedetailsimg() == null : this.getFranchisedetailsimg().equals(other.getFranchisedetailsimg()))
            && (this.getFranchisedetailscreattime() == null ? other.getFranchisedetailscreattime() == null : this.getFranchisedetailscreattime().equals(other.getFranchisedetailscreattime()))
            && (this.getFranchisedetailscontent() == null ? other.getFranchisedetailscontent() == null : this.getFranchisedetailscontent().equals(other.getFranchisedetailscontent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFranchisedetailsid() == null) ? 0 : getFranchisedetailsid().hashCode());
        result = prime * result + ((getFranchisedetailsimg() == null) ? 0 : getFranchisedetailsimg().hashCode());
        result = prime * result + ((getFranchisedetailscreattime() == null) ? 0 : getFranchisedetailscreattime().hashCode());
        result = prime * result + ((getFranchisedetailscontent() == null) ? 0 : getFranchisedetailscontent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FranchiseDetails
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", franchisedetailsid=").append(franchisedetailsid);
        sb.append(", franchisedetailsimg=").append(franchisedetailsimg);
        sb.append(", franchisedetailscreattime=").append(franchisedetailscreattime);
        sb.append(", franchisedetailscontent=").append(franchisedetailscontent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}