package com.shensu.pojo;

import java.io.Serializable;
import java.util.List;

public class RecipesType implements Serializable {

	//分类的id
    private Integer recipestypeid;

    //食谱的创建时间
    private String recipestypecreattime;

    // 食谱类目
    private String recipestypename;

    //0是下架 1是上架
    private Integer recipestypestate;

    //分类的图片
    private String recipsetypeimg;
    
    //食谱集合
    List<Recipes> recipesList;
    

    public List<Recipes> getRecipesList() {
		return recipesList;
	}

	public void setRecipesList(List<Recipes> recipesList) {
		this.recipesList = recipesList;
	}

	private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecipesType.recipesTypeId
     *
     * @return the value of RecipesType.recipesTypeId
     *
     * @mbggenerated
     */
    public Integer getRecipestypeid() {
        return recipestypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecipesType.recipesTypeId
     *
     * @param recipestypeid the value for RecipesType.recipesTypeId
     *
     * @mbggenerated
     */
    public void setRecipestypeid(Integer recipestypeid) {
        this.recipestypeid = recipestypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecipesType.recipesTypeCreatTime
     *
     * @return the value of RecipesType.recipesTypeCreatTime
     *
     * @mbggenerated
     */
    public String getRecipestypecreattime() {
        return recipestypecreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecipesType.recipesTypeCreatTime
     *
     * @param recipestypecreattime the value for RecipesType.recipesTypeCreatTime
     *
     * @mbggenerated
     */
    public void setRecipestypecreattime(String recipestypecreattime) {
        this.recipestypecreattime = recipestypecreattime == null ? null : recipestypecreattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecipesType.recipesTypeName
     *
     * @return the value of RecipesType.recipesTypeName
     *
     * @mbggenerated
     */
    public String getRecipestypename() {
        return recipestypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecipesType.recipesTypeName
     *
     * @param recipestypename the value for RecipesType.recipesTypeName
     *
     * @mbggenerated
     */
    public void setRecipestypename(String recipestypename) {
        this.recipestypename = recipestypename == null ? null : recipestypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecipesType.recipesTypeState
     *
     * @return the value of RecipesType.recipesTypeState
     *
     * @mbggenerated
     */
    public Integer getRecipestypestate() {
        return recipestypestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecipesType.recipesTypeState
     *
     * @param recipestypestate the value for RecipesType.recipesTypeState
     *
     * @mbggenerated
     */
    public void setRecipestypestate(Integer recipestypestate) {
        this.recipestypestate = recipestypestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecipesType.recipseTypeImg
     *
     * @return the value of RecipesType.recipseTypeImg
     *
     * @mbggenerated
     */
    public String getRecipsetypeimg() {
        return recipsetypeimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecipesType.recipseTypeImg
     *
     * @param recipsetypeimg the value for RecipesType.recipseTypeImg
     *
     * @mbggenerated
     */
    public void setRecipsetypeimg(String recipsetypeimg) {
        this.recipsetypeimg = recipsetypeimg == null ? null : recipsetypeimg.trim();
    }

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RecipesType other = (RecipesType) obj;
		if (recipesList == null) {
			if (other.recipesList != null)
				return false;
		} else if (!recipesList.equals(other.recipesList))
			return false;
		if (recipestypecreattime == null) {
			if (other.recipestypecreattime != null)
				return false;
		} else if (!recipestypecreattime.equals(other.recipestypecreattime))
			return false;
		if (recipestypeid == null) {
			if (other.recipestypeid != null)
				return false;
		} else if (!recipestypeid.equals(other.recipestypeid))
			return false;
		if (recipestypename == null) {
			if (other.recipestypename != null)
				return false;
		} else if (!recipestypename.equals(other.recipestypename))
			return false;
		if (recipestypestate == null) {
			if (other.recipestypestate != null)
				return false;
		} else if (!recipestypestate.equals(other.recipestypestate))
			return false;
		if (recipsetypeimg == null) {
			if (other.recipsetypeimg != null)
				return false;
		} else if (!recipsetypeimg.equals(other.recipsetypeimg))
			return false;
		return true;
	}

    @Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((recipesList == null) ? 0 : recipesList.hashCode());
		result = prime * result + ((recipestypecreattime == null) ? 0 : recipestypecreattime.hashCode());
		result = prime * result + ((recipestypeid == null) ? 0 : recipestypeid.hashCode());
		result = prime * result + ((recipestypename == null) ? 0 : recipestypename.hashCode());
		result = prime * result + ((recipestypestate == null) ? 0 : recipestypestate.hashCode());
		result = prime * result + ((recipsetypeimg == null) ? 0 : recipsetypeimg.hashCode());
		return result;
	}

    @Override
	public String toString() {
		return "RecipesType [recipestypeid=" + recipestypeid + ", recipestypecreattime=" + recipestypecreattime
				+ ", recipestypename=" + recipestypename + ", recipestypestate=" + recipestypestate
				+ ", recipsetypeimg=" + recipsetypeimg + ", recipesList=" + recipesList + "]";
	}
}