package com.shensu.pojo;

import java.io.Serializable;
import java.util.List;

public class ShopSKU implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSKU.shopSKUId
     *
     * @mbggenerated  
     */
	//商品的skuid
    private Integer shopskuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSKU.shopId
     *
     * @mbggenerated 
     */
    //商品的id
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSKU.shopSKUSpecifications
     *
     * @mbggenerated  
     */ 
    //规格
    private String shopskuspecifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSKU.shopSKU
     *
     * @mbggenerated 
     */
    //sku唯一标识
    private String shopsku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSKU.shopSKUImg
     *
     * @mbggenerated
     */
    // sku切换的地址
    private String shopskuimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSKU.shopSKUMoney
     *
     * @mbggenerated 
     */
    //sku商品的价格
    private Float shopskumoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSKU.shopSKUStock
     *
     * @mbggenerated  
     */
    //商品的sku的库存
    private Integer shopskustock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSKU.shopSKUTime
     *
     * @mbggenerated 
     */
    //sku创建时间
    private String shopskutime;
    
    private List<ShopSkuSwiper> shopSkuSwiper;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ShopSKU
     *
     * @mbggenerated
     */
    
    private static final long serialVersionUID = 1L;

    /**
	 * @return shopSkuSwiper
	 */
	public List<ShopSkuSwiper> getShopSkuSwiper() {
		return shopSkuSwiper;
	}

	/**
	 * @param shopSkuSwiper 要设置的 shopSkuSwiper
	 */
	public void setShopSkuSwiper(List<ShopSkuSwiper> shopSkuSwiper) {
		this.shopSkuSwiper = shopSkuSwiper;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSKU.shopSKUId
     *
     * @return the value of ShopSKU.shopSKUId
     *
     * @mbggenerated
     */
    public Integer getShopskuid() {
        return shopskuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSKU.shopSKUId
     *
     * @param shopskuid the value for ShopSKU.shopSKUId
     *
     * @mbggenerated
     */
    public void setShopskuid(Integer shopskuid) {
        this.shopskuid = shopskuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSKU.shopId
     *
     * @return the value of ShopSKU.shopId
     *
     * @mbggenerated
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSKU.shopId
     *
     * @param shopid the value for ShopSKU.shopId
     *
     * @mbggenerated
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSKU.shopSKUSpecifications
     *
     * @return the value of ShopSKU.shopSKUSpecifications
     *
     * @mbggenerated
     */
    public String getShopskuspecifications() {
        return shopskuspecifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSKU.shopSKUSpecifications
     *
     * @param shopskuspecifications the value for ShopSKU.shopSKUSpecifications
     *
     * @mbggenerated
     */
    public void setShopskuspecifications(String shopskuspecifications) {
        this.shopskuspecifications = shopskuspecifications == null ? null : shopskuspecifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSKU.shopSKU
     *
     * @return the value of ShopSKU.shopSKU
     *
     * @mbggenerated
     */
    public String getShopsku() {
        return shopsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSKU.shopSKU
     *
     * @param shopsku the value for ShopSKU.shopSKU
     *
     * @mbggenerated
     */
    public void setShopsku(String shopsku) {
        this.shopsku = shopsku == null ? null : shopsku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSKU.shopSKUImg
     *
     * @return the value of ShopSKU.shopSKUImg
     *
     * @mbggenerated
     */
    public String getShopskuimg() {
        return shopskuimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSKU.shopSKUImg
     *
     * @param shopskuimg the value for ShopSKU.shopSKUImg
     *
     * @mbggenerated
     */
    public void setShopskuimg(String shopskuimg) {
        this.shopskuimg = shopskuimg == null ? null : shopskuimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSKU.shopSKUMoney
     *
     * @return the value of ShopSKU.shopSKUMoney
     *
     * @mbggenerated
     */
    public Float getShopskumoney() {
        return shopskumoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSKU.shopSKUMoney
     *
     * @param shopskumoney the value for ShopSKU.shopSKUMoney
     *
     * @mbggenerated
     */
    public void setShopskumoney(Float shopskumoney) {
        this.shopskumoney = shopskumoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSKU.shopSKUStock
     *
     * @return the value of ShopSKU.shopSKUStock
     *
     * @mbggenerated
     */
    public Integer getShopskustock() {
        return shopskustock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSKU.shopSKUStock
     *
     * @param shopskustock the value for ShopSKU.shopSKUStock
     *
     * @mbggenerated
     */
    public void setShopskustock(Integer shopskustock) {
        this.shopskustock = shopskustock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSKU.shopSKUTime
     *
     * @return the value of ShopSKU.shopSKUTime
     *
     * @mbggenerated
     */
    public String getShopskutime() {
        return shopskutime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSKU.shopSKUTime
     *
     * @param shopskutime the value for ShopSKU.shopSKUTime
     *
     * @mbggenerated
     */
    public void setShopskutime(String shopskutime) {
        this.shopskutime = shopskutime == null ? null : shopskutime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSKU
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShopSKU other = (ShopSKU) that;
        return (this.getShopskuid() == null ? other.getShopskuid() == null : this.getShopskuid().equals(other.getShopskuid()))
            && (this.getShopid() == null ? other.getShopid() == null : this.getShopid().equals(other.getShopid()))
            && (this.getShopskuspecifications() == null ? other.getShopskuspecifications() == null : this.getShopskuspecifications().equals(other.getShopskuspecifications()))
            && (this.getShopsku() == null ? other.getShopsku() == null : this.getShopsku().equals(other.getShopsku()))
            && (this.getShopskuimg() == null ? other.getShopskuimg() == null : this.getShopskuimg().equals(other.getShopskuimg()))
            && (this.getShopskumoney() == null ? other.getShopskumoney() == null : this.getShopskumoney().equals(other.getShopskumoney()))
            && (this.getShopskustock() == null ? other.getShopskustock() == null : this.getShopskustock().equals(other.getShopskustock()))
            && (this.getShopskutime() == null ? other.getShopskutime() == null : this.getShopskutime().equals(other.getShopskutime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSKU
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShopskuid() == null) ? 0 : getShopskuid().hashCode());
        result = prime * result + ((getShopid() == null) ? 0 : getShopid().hashCode());
        result = prime * result + ((getShopskuspecifications() == null) ? 0 : getShopskuspecifications().hashCode());
        result = prime * result + ((getShopsku() == null) ? 0 : getShopsku().hashCode());
        result = prime * result + ((getShopskuimg() == null) ? 0 : getShopskuimg().hashCode());
        result = prime * result + ((getShopskumoney() == null) ? 0 : getShopskumoney().hashCode());
        result = prime * result + ((getShopskustock() == null) ? 0 : getShopskustock().hashCode());
        result = prime * result + ((getShopskutime() == null) ? 0 : getShopskutime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSKU
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shopskuid=").append(shopskuid);
        sb.append(", shopid=").append(shopid);
        sb.append(", shopskuspecifications=").append(shopskuspecifications);
        sb.append(", shopsku=").append(shopsku);
        sb.append(", shopskuimg=").append(shopskuimg);
        sb.append(", shopskumoney=").append(shopskumoney);
        sb.append(", shopskustock=").append(shopskustock);
        sb.append(", shopskutime=").append(shopskutime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}