package com.shensu.pojo;

import java.io.Serializable;

public class ShopSwiper implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSwiper.shopSwiperId
     *
     * @mbggenerated  
     */
	//商品的轮播图的id
    private Integer shopswiperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSwiper.shopSwiperImg
     *
     * @mbggenerated
     */
    // 轮播图的地址
    private String shopswiperimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSwiper.shopId
     *
     * @mbggenerated  
     */
    //商品的id
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ShopSwiper.shopSwiperCreatTime
     *
     * @mbggenerated  
     */
    //商品的轮播图的创建时间
    private String shopswipercreattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSwiper.shopSwiperId
     *
     * @return the value of ShopSwiper.shopSwiperId
     *
     * @mbggenerated
     */
    public Integer getShopswiperid() {
        return shopswiperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSwiper.shopSwiperId
     *
     * @param shopswiperid the value for ShopSwiper.shopSwiperId
     *
     * @mbggenerated
     */
    public void setShopswiperid(Integer shopswiperid) {
        this.shopswiperid = shopswiperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSwiper.shopSwiperImg
     *
     * @return the value of ShopSwiper.shopSwiperImg
     *
     * @mbggenerated
     */
    public String getShopswiperimg() {
        return shopswiperimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSwiper.shopSwiperImg
     *
     * @param shopswiperimg the value for ShopSwiper.shopSwiperImg
     *
     * @mbggenerated
     */
    public void setShopswiperimg(String shopswiperimg) {
        this.shopswiperimg = shopswiperimg == null ? null : shopswiperimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSwiper.shopId
     *
     * @return the value of ShopSwiper.shopId
     *
     * @mbggenerated
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSwiper.shopId
     *
     * @param shopid the value for ShopSwiper.shopId
     *
     * @mbggenerated
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ShopSwiper.shopSwiperCreatTime
     *
     * @return the value of ShopSwiper.shopSwiperCreatTime
     *
     * @mbggenerated
     */
    public String getShopswipercreattime() {
        return shopswipercreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ShopSwiper.shopSwiperCreatTime
     *
     * @param shopswipercreattime the value for ShopSwiper.shopSwiperCreatTime
     *
     * @mbggenerated
     */
    public void setShopswipercreattime(String shopswipercreattime) {
        this.shopswipercreattime = shopswipercreattime == null ? null : shopswipercreattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ShopSwiper other = (ShopSwiper) that;
        return (this.getShopswiperid() == null ? other.getShopswiperid() == null : this.getShopswiperid().equals(other.getShopswiperid()))
            && (this.getShopswiperimg() == null ? other.getShopswiperimg() == null : this.getShopswiperimg().equals(other.getShopswiperimg()))
            && (this.getShopid() == null ? other.getShopid() == null : this.getShopid().equals(other.getShopid()))
            && (this.getShopswipercreattime() == null ? other.getShopswipercreattime() == null : this.getShopswipercreattime().equals(other.getShopswipercreattime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShopswiperid() == null) ? 0 : getShopswiperid().hashCode());
        result = prime * result + ((getShopswiperimg() == null) ? 0 : getShopswiperimg().hashCode());
        result = prime * result + ((getShopid() == null) ? 0 : getShopid().hashCode());
        result = prime * result + ((getShopswipercreattime() == null) ? 0 : getShopswipercreattime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ShopSwiper
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shopswiperid=").append(shopswiperid);
        sb.append(", shopswiperimg=").append(shopswiperimg);
        sb.append(", shopid=").append(shopid);
        sb.append(", shopswipercreattime=").append(shopswipercreattime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}