package com.shensu.pojo;

import java.io.Serializable;

public class Swiper implements Serializable {
	
	//轮播图位置
	private int location;
	//绑定项目id
	private int shopId;
	
    public int getLocation() {
		return location;
	}

	public void setLocation(int location) {
		this.location = location;
	}

	public int getShopId() {
		return shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Swiper.swiperId
     *
     * @mbggenerated
     */
	//轮播图id
    private Integer swiperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Swiper.swiperImg
     *
     * @mbggenerated
     */
    //轮播图的图片地址
    private String swiperimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Swiper.swiperCreatTime
     *
     * @mbggenerated
     */
     //轮播图的创建时间
    private String swipercreattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Swiper
     *
     * @mbggenerated
     */
    
     private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Swiper.swiperId
     *
     * @return the value of Swiper.swiperId
     *
     * @mbggenerated
     */
    public Integer getSwiperid() {
        return swiperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Swiper.swiperId
     *
     * @param swiperid the value for Swiper.swiperId
     *
     * @mbggenerated
     */
    public void setSwiperid(Integer swiperid) {
        this.swiperid = swiperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Swiper.swiperImg
     *
     * @return the value of Swiper.swiperImg
     *
     * @mbggenerated
     */
    public String getSwiperimg() {
        return swiperimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Swiper.swiperImg
     *
     * @param swiperimg the value for Swiper.swiperImg
     *
     * @mbggenerated
     */
    public void setSwiperimg(String swiperimg) {
        this.swiperimg = swiperimg == null ? null : swiperimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Swiper.swiperCreatTime
     *
     * @return the value of Swiper.swiperCreatTime
     *
     * @mbggenerated
     */
    public String getSwipercreattime() {
        return swipercreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Swiper.swiperCreatTime
     *
     * @param swipercreattime the value for Swiper.swiperCreatTime
     *
     * @mbggenerated
     */
    public void setSwipercreattime(String swipercreattime) {
        this.swipercreattime = swipercreattime == null ? null : swipercreattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Swiper
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Swiper other = (Swiper) that;
        return (this.getSwiperid() == null ? other.getSwiperid() == null : this.getSwiperid().equals(other.getSwiperid()))
            && (this.getSwiperimg() == null ? other.getSwiperimg() == null : this.getSwiperimg().equals(other.getSwiperimg()))
            && (this.getSwipercreattime() == null ? other.getSwipercreattime() == null : this.getSwipercreattime().equals(other.getSwipercreattime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Swiper
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSwiperid() == null) ? 0 : getSwiperid().hashCode());
        result = prime * result + ((getSwiperimg() == null) ? 0 : getSwiperimg().hashCode());
        result = prime * result + ((getSwipercreattime() == null) ? 0 : getSwipercreattime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Swiper
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", swiperid=").append(swiperid);
        sb.append(", swiperimg=").append(swiperimg);
        sb.append(", swipercreattime=").append(swipercreattime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }


}