package com.shensu.pojo;

import java.io.Serializable;

public class Template implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Template.templateId
     *
     * @mbggenerated
     */
	//模版的的id
    private Integer templateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Template.temolateTitle
     *
     * @mbggenerated
     */
    //模版的模版的title
    private String temolatetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Template.templateContent
     *
     * @mbggenerated
     */
    //模版的内容
    private String templatecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Template.templateCreatTime
     *
     * @mbggenerated
     */
    //模版的创建的时间
    private String templatecreattime;
    
    private String form_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Template
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Template.templateId
     *
     * @return the value of Template.templateId
     *
     * @mbggenerated
     */
    public Integer getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Template.templateId
     *
     * @param templateid the value for Template.templateId
     *
     * @mbggenerated
     */
    public void setTemplateid(Integer templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Template.temolateTitle
     *
     * @return the value of Template.temolateTitle
     *
     * @mbggenerated
     */
    public String getTemolatetitle() {
        return temolatetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Template.temolateTitle
     *
     * @param temolatetitle the value for Template.temolateTitle
     *
     * @mbggenerated
     */
    public void setTemolatetitle(String temolatetitle) {
        this.temolatetitle = temolatetitle == null ? null : temolatetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Template.templateContent
     *
     * @return the value of Template.templateContent
     *
     * @mbggenerated
     */
    public String getTemplatecontent() {
        return templatecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Template.templateContent
     *
     * @param templatecontent the value for Template.templateContent
     *
     * @mbggenerated
     */
    public void setTemplatecontent(String templatecontent) {
        this.templatecontent = templatecontent == null ? null : templatecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Template.templateCreatTime
     *
     * @return the value of Template.templateCreatTime
     *
     * @mbggenerated
     */
    public String getTemplatecreattime() {
        return templatecreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Template.templateCreatTime
     *
     * @param templatecreattime the value for Template.templateCreatTime
     *
     * @mbggenerated
     */
    public void setTemplatecreattime(String templatecreattime) {
        this.templatecreattime = templatecreattime == null ? null : templatecreattime.trim();
    }

	/**
	 * @return form_id
	 */
	public String getForm_id() {
		return form_id;
	}

	/**
	 * @return serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @param form_id 要设置的 form_id
	 */

	/* （非 Javadoc）
	 * @see java.lang.Object#toString()
	 * 
	 * toString
	 */
	@Override
	public String toString() {
		return "Template [templateid=" + templateid + ", temolatetitle=" + temolatetitle + ", templatecontent="
				+ templatecontent + ", templatecreattime=" + templatecreattime + ", form_id=" + form_id + "]";
	}

	/**
	 * @param form_id 要设置的 form_id
	 */
	public void setForm_id(String form_id) {
		this.form_id = form_id;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Template
     *
     * @mbggenerated
     */

}